// <auto-generated />
using System;
using DashboardProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DashboardProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260618073443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DashboardProject.Models.Entities.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("DashboardProject.Models.Entities.DashboardWidget", b =>
                {
                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WidgetId")
                        .HasColumnType("uuid");

                    b.HasKey("DashboardId", "WidgetId");

                    b.HasIndex("WidgetId");

                    b.ToTable("DashboardWidgets");
                });

            modelBuilder.Entity("DashboardProject.Models.Entities.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Widgets");
                });

            modelBuilder.Entity("DashboardProject.Models.Entities.DashboardWidget", b =>
                {
                    b.HasOne("DashboardProject.Models.Entities.Dashboard", "Dashboard")
                        .WithMany("DashboardWidget")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DashboardProject.Models.Entities.Widget", "Widget")
                        .WithMany("DashboardWidget")
                        .HasForeignKey("WidgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dashboard");

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("DashboardProject.Models.Entities.Dashboard", b =>
                {
                    b.Navigation("DashboardWidget");
                });

            modelBuilder.Entity("DashboardProject.Models.Entities.Widget", b =>
                {
                    b.Navigation("DashboardWidget");
                });
#pragma warning restore 612, 618
        }
    }
}
